sonar.projectKey=alimenta-plus-auth
sonar.projectName=Alimenta+ Auth Service
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

sonar.sources=services/auth-service/src
sonar.tests=services/auth-service/tests
sonar.javascript.lcov.reportPaths=services/auth-service/coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/coverage/**
sonar.coverage.exclusions=**/server.js
